# Generated by Django 2.2.13 on 2020-06-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fintech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transactions_id',
            new_name='transaction_id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_fintech.Statuses'),
        ),
    ]
